# This is a TOML document
title = "Cleandir Test Config"

[Downloads]
directory = "~/Downloads"
target-prefix = "%Y-%m"

[Downloads.pdf]
enabled = true
extension = "pdf"
target = "PDF"

[Downloads.images]
enabled = true
extensions = ["jpeg", "jpg", "png"]
target = "images"

[Downloads.office]
enabled = true
extensions = ["odt", "doc", "docx", "ppt", "pptx" ]
target= "office"
